FROM node:20-alpine AS builder
WORKDIR /frontend
COPY package*.json ./
RUN npm install


FROM node:20-alpine
WORKDIR /frontend
COPY --from=builder /frontend/node_modules ./node_modules
COPY . .
EXPOSE 5173
CMD ["npm", "start"]